# Generated by Django 3.1.6 on 2021-02-11 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source_reference_models_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Src_afe_type',
            fields=[
                ('ref_afe_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('afe_type', models.CharField(max_length=255, unique=True)),
                ('afe_type_descrip', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'src_afe_type',
            },
        ),
        migrations.AddField(
            model_name='audit_historical_src_tbl_deal_seller',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audit_historical_src_tbl_deal_seller',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='src_tbl_deal_seller',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_seller_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='src_tbl_deal_seller',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_seller_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
